/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BookingId = bigint;
export interface BookingInput {
  'serviceType' : ServiceType,
  'date' : Time,
  'name' : string,
  'expertId' : bigint,
  'address' : string,
  'notes' : string,
  'phone' : string,
}
export interface BookingOutput {
  'id' : BookingId,
  'status' : Status,
  'serviceType' : ServiceType,
  'date' : Time,
  'name' : string,
  'createdAt' : Time,
  'expertId' : bigint,
  'updatedAt' : Time,
  'address' : string,
  'notes' : string,
  'phone' : string,
}
export interface Expert {
  'id' : bigint,
  'name' : string,
  'experience' : bigint,
  'appointmentsDone' : bigint,
  'rating' : number,
}
export type ServiceType = { 'acrylicNails' : null } |
  { 'pedicure' : null } |
  { 'gelNails' : null } |
  { 'manicure' : null };
export type Status = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllBookings' : ActorMethod<[], Array<BookingOutput>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExperts' : ActorMethod<[], Array<Expert>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitBooking' : ActorMethod<[BookingInput], bigint>,
  'updateBookingStatus' : ActorMethod<[bigint, Status], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];